# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(552, 400)
        Dialog.setStyleSheet("background-color: rgb(53, 53, 53);\n"
"color: rgb(0, 170, 255);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(250, 240, 141, 20))
        self.label_5.setObjectName("label_5")
        self.accept = QtWidgets.QPushButton(Dialog)
        self.accept.setGeometry(QtCore.QRect(310, 360, 101, 23))
        self.accept.setObjectName("accept")
        self.spinBox_2 = QtWidgets.QSpinBox(Dialog)
        self.spinBox_2.setGeometry(QtCore.QRect(400, 100, 101, 22))
        self.spinBox_2.setMinimum(1)
        self.spinBox_2.setProperty("value", 10)
        self.spinBox_2.setObjectName("spinBox_2")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(140, 160, 381, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(270, 50, 121, 20))
        self.label.setObjectName("label")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(370, 270, 31, 20))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(270, 310, 111, 20))
        self.label_7.setObjectName("label_7")
        self.spinBox_4 = QtWidgets.QSpinBox(Dialog)
        self.spinBox_4.setGeometry(QtCore.QRect(400, 190, 101, 22))
        self.spinBox_4.setMinimum(1)
        self.spinBox_4.setProperty("value", 5)
        self.spinBox_4.setObjectName("spinBox_4")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(270, 190, 121, 20))
        self.label_4.setObjectName("label_4")
        self.spinBox_3 = QtWidgets.QSpinBox(Dialog)
        self.spinBox_3.setGeometry(QtCore.QRect(400, 130, 101, 22))
        self.spinBox_3.setMinimum(1)
        self.spinBox_3.setProperty("value", 10)
        self.spinBox_3.setObjectName("spinBox_3")
        self.cancel = QtWidgets.QPushButton(Dialog)
        self.cancel.setGeometry(QtCore.QRect(420, 360, 91, 23))
        self.cancel.setObjectName("cancel")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(360, 130, 31, 20))
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(250, 100, 141, 20))
        self.label_2.setObjectName("label_2")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(80, 30, 111, 20))
        self.label_8.setObjectName("label_8")
        self.spinBox_5 = QtWidgets.QSpinBox(Dialog)
        self.spinBox_5.setGeometry(QtCore.QRect(400, 240, 101, 22))
        self.spinBox_5.setMinimum(1)
        self.spinBox_5.setSingleStep(1)
        self.spinBox_5.setProperty("value", 20)
        self.spinBox_5.setObjectName("spinBox_5")
        self.spinBox = QtWidgets.QSpinBox(Dialog)
        self.spinBox.setGeometry(QtCore.QRect(400, 50, 101, 22))
        self.spinBox.setMinimum(1)
        self.spinBox.setObjectName("spinBox")
        self.spinBox_7 = QtWidgets.QSpinBox(Dialog)
        self.spinBox_7.setGeometry(QtCore.QRect(400, 310, 101, 22))
        self.spinBox_7.setMinimum(100)
        self.spinBox_7.setMaximum(10000)
        self.spinBox_7.setProperty("value", 500)
        self.spinBox_7.setObjectName("spinBox_7")
        self.spinBox_6 = QtWidgets.QSpinBox(Dialog)
        self.spinBox_6.setGeometry(QtCore.QRect(400, 270, 101, 22))
        self.spinBox_6.setMinimum(1)
        self.spinBox_6.setProperty("value", 20)
        self.spinBox_6.setObjectName("spinBox_6")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(80, 190, 91, 16))
        self.label_9.setObjectName("label_9")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_5.setText(_translate("Dialog", "3D functions- x:   1/"))
        self.accept.setText(_translate("Dialog", "Accept"))
        self.label.setText(_translate("Dialog", "2D functions:   1/"))
        self.label_6.setText(_translate("Dialog", "y:   1/"))
        self.label_7.setText(_translate("Dialog", "Step (Millis):"))
        self.label_4.setText(_translate("Dialog", "2D functions:   1/"))
        self.cancel.setText(_translate("Dialog", "Close"))
        self.label_3.setText(_translate("Dialog", "y:   1/"))
        self.label_2.setText(_translate("Dialog", "3D functions- x:   1/"))
        self.label_8.setText(_translate("Dialog", "Visualization:"))
        self.label_9.setText(_translate("Dialog", "Animation:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
